### PR TITLE
Removing type parameter

### PR DESCRIPTION
**Pull request by surajatreya**
Removing an unnecessary type parameter

### CODE REVIEW

**Comment by daschl** [comment]
paging @programmatix

**Comment by surajatreya** [comment]
Thanks @programmatix . Although, I didn't quite get what you mean by this is not a PR. You can merge the change if you are fine.

**Comment by programmatix** [comment]
Apologies for the confusion @surajatreya, it is indeed a PR.  I was looking at the commit in different location in github that didn't make it super-clear it was part of a PR (e.g. it just showed the individual commit).

Anyway, I'm good with this change but don't have write permissions on the repo to accept it.  @daschl do you?

**Comment by daschl** [comment]
@programmatix this needs to go through gerrit - github is just a mirror.

@surajatreya can you please follow the instructions in https://github.com/couchbase/couchbase-java-client/blob/master/CONTRIBUTING.md ? (and submit it to the couchbase-jvm-clients repo, the rest is identical)

**Comment by programmatix** [comment]
I've gone ahead and made the change in http://review.couchbase.org/#/c/118055/.  @surajatreya thank you for the submission.

**Pull request closed without merging**
